### ISSUE TITLE
install with CurseBreaker?

### ISSUE THREAD

**Issue by derschneidertom** [Kkthnx-Wow/KkthnxUI_TBC#1]
i use CurseBreaker to install all my Addons.
your KkthnxUI runs nice at Version 10.1.6.
but can i install the TBC Version with CurseBreaker also?
regards tom

**Comment by Kkthnx** [comment]
Ill start packaging it on GitHub to allow this. I keep forgetting about doing so. Thank you.

**Comment by derschneidertom** [comment]
thx…

Von: Kkthnx ***@***.***>
Gesendet: Montag, 7. Juni 2021 04:15
An: Kkthnx-Wow/KkthnxUI_TBC ***@***.***>
Cc: derschneidertom ***@***.***>; Author ***@***.***>
Betreff: Re: [Kkthnx-Wow/KkthnxUI_TBC] install with CurseBreaker? (#1)


Ill start packaging it on GitHub to allow this. I keep forgetting about doing so. Thank you.
